### ISSUE TITLE
wrong url in 'effect module' error messages

### ISSUE THREAD

**Issue by srghma** [elm/compiler#1603]
`effect modules here: <http://guide.elm-lang.org/effect_managers/>` leads to unexisting page
P.S. 
it would be awesome to have some guide about `effect module` and how to use it 
for example if look how websocket implemented I cant find from where does [command](https://github.com/elm-lang/websocket/blob/master/src/WebSocket.elm#L52) and [subscription](https://github.com/elm-lang/websocket/blob/master/src/WebSocket.elm#L83) comes from, what is their type?

Error sample: 
```
ERROR in ./src/elm/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
-- EFFECT MODULE PROBLEM - /home/bjorn/projects/spaceshooter-elm/src/elm/Main.elm

You are defining an effect module, but there is no `subMap` defined.

1| effect module Main where { subscription = MySub } exposing (..)
   ^^^^^^^^^^^^^
There is a small set of top-level functions and values that must be defined in
any complete effect module. The best thing is probably to just read more about
effect modules here: <http://guide.elm-lang.org/effect_managers/>

-- EFFECT MODULE PROBLEM - /home/bjorn/projects/spaceshooter-elm/src/elm/Main.elm

You are defining an effect module, but there is no `onEffects` defined.

1| effect module Main where { subscription = MySub } exposing (..)
   ^^^^^^^^^^^^^
There is a small set of top-level functions and values that must be defined in
any complete effect module. The best thing is probably to just read more about
effect modules here: <http://guide.elm-lang.org/effect_managers/>

-- EFFECT MODULE PROBLEM - /home/bjorn/projects/spaceshooter-elm/src/elm/Main.elm

You are defining an effect module, but there is no `onSelfMsg` defined.

1| effect module Main where { subscription = MySub } exposing (..)
   ^^^^^^^^^^^^^
There is a small set of top-level functions and values that must be defined in
any complete effect module. The best thing is probably to just read more about
effect modules here: <http://guide.elm-lang.org/effect_managers/>

Detected errors in 1 module.

    at ChildProcess.<anonymous> (/home/bjorn/projects/spaceshooter-elm/node_modules/node-elm-compiler/index.js:141:27)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
 @ ./src/static/index.js 7:10-34

```
Elm version 0.18

**Comment by evancz** [comment]
Effect modules are no longer generally available. I don't exactly recall if a special error message is given if people try to make them still, but there wouldn't be a link about it anymore.
