### ISSUE TITLE
ELIFECYCLE for npm install elm@latest-0.18.0

### ISSUE THREAD

**Issue by mpizenberg** [elm/compiler#2118]
Creating an empty directory and running `npm install elm@latest-0.18.0` inside returns the ELIFECYCLE error whereas the `latest-0.19.1` has no issue.

I'm using archlinux and node 12.9.1 installed via [fish-nvm](https://github.com/jorgebucaran/fish-nvm).

Here is the npm log

```
2180 verbose stack Error: elm@0.18.0-exp5 install: `npx binwrap-install`
2180 verbose stack Exit status 1
2180 verbose stack     at EventEmitter.<anonymous> (/home/matthieu/.config/nvm/12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
2180 verbose stack     at EventEmitter.emit (events.js:209:13)
2180 verbose stack     at ChildProcess.<anonymous> (/home/matthieu/.config/nvm/12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2180 verbose stack     at ChildProcess.emit (events.js:209:13)
2180 verbose stack     at maybeClose (internal/child_process.js:1021:16)
2180 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2181 verbose pkgid elm@0.18.0-exp5
2182 verbose cwd /home/matthieu/temp/elm/npm
2183 verbose Linux 5.4.45-1-lts
2184 verbose argv "/home/matthieu/.config/nvm/12.9.1/bin/node" "/home/matthieu/.config/nvm/12.9.1/bin/npm" "install" "elm@latest-0.18.0"
2185 verbose node v12.9.1
2186 verbose npm  v6.10.2
2187 error code ELIFECYCLE
2188 error errno 1
2189 error elm@0.18.0-exp5 install: `npx binwrap-install`
2189 error Exit status 1
2190 error Failed at the elm@0.18.0-exp5 install script.
2190 error This is probably not a problem with npm. There is likely additional logging output above.
2191 verbose exit [ 1, true ]
```

**Comment by lydell** [comment]
I recently tried a couple of things out with Elm 0.18 and needed to use Node.js 10 in order to install it from npm.

**Comment by mpizenberg** [comment]
Indeed this seems to be working with node 10 but not with 12 or 14. Thanks for the tips!
