### ISSUE TITLE
npm/yarn install fails: Linux binaries for 0.18.0 no longer available

### ISSUE THREAD

**Issue by bridj-drolin** [elm/compiler#2199]
**Quick Summary:** 
`npm install elm@latest-0.18.0` fails with the following error

```
Command: node install.js
Arguments:
Directory: /bridj/node_modules/elm-webpack-loader/node_modules/elm
Output:
Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz
Error decompressing linux-x64.tar.gz Error: incorrect header check
    at ProcessTermError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:243:66)
    at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:272:123)
    at new ProcessTermError (/usr/share/yarn/lib/cli.js:312:113)
    at ChildProcess.<anonymous> (/usr/share/yarn/lib/cli.js:24408:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error /bridj/node_modules/elm-webpack-loader/node_modules/elm: Command failed.
Exit code: 1
```

- **Elm:** 0.18
- **Browser:** n/a
- **Operating System:** Centos7

https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz currently returns a 403 status code.

**Comment by bridj-drolin** [comment]
For anyone having the same issue, see this thread on Discourse: https://discourse.elm-lang.org/t/psa-old-elm-binary-downloads-now-gone/7319/7

> Elm 0.18 and older binaries were hosted on something called Bintray. That service was sunset yesterday: Service End for Bintray, JCenter, GoCenter, and ChartCenter | JFrog 6
