### ISSUE TITLE
Adding type_ attr to textarea throws error in runtime

### ISSUE THREAD

**Issue by hariroshan** [elm/compiler#2245]
**Quick Summary:**  I know we are not suppose to add `type_` attr to textarea. But It was not caught during compile time and crashes runtime when the code is reached.

## SSCCE

```elm
textarea
        [  type_ "text" 
         , class "hello"  
        ]
        []

```

- **Elm:** 0.19.1
- **Browser:** Microsoft Edge Version 98.0.1108.56 (Official build) (x86_64) 
- **Operating System:** mac OS Catalina 10.15.7

## Additional Details
```
    Uncaught TypeError: Cannot set property type of #<HTMLTextAreaElement> which has only a getter
    at _VirtualDom_applyFacts (elm.js:2842:87)
    at _VirtualDom_render (elm.js:2809:2)
    at _VirtualDom_render (elm.js:2813:36)
    at _VirtualDom_render (elm.js:2813:36)
    at _VirtualDom_render (elm.js:2813:36)
    at _VirtualDom_render (elm.js:2813:36)
    at _VirtualDom_render (elm.js:2813:36)
    at _VirtualDom_render (elm.js:2786:17)
    at _VirtualDom_applyPatch (elm.js:3755:26)
    at _VirtualDom_applyPatchesHelp (elm.js:3702:17)
```

**Comment by jfmengels** [comment]
This issue is probably better reported in [elm/virtual-dom](https://github.com/elm/virtual-dom).
